Add ContentLocale method to Security controller
silverstripe/silverstripe-login-forms pull request #101
Opened 2021-09-06 15:11 UTC by TheBnl

New PR on Security extension instead on framework base Controller as requested #100

2021-09-07 04:25 UTC, emteknetnz requested changes
There's a couple of PHPCS failures

For the long line one, just wrap line 80 over 2 lines

For the other, could you update the phpcs.xml.dist file in this module so that it allows non camel cased method names i.e. https://github.com/silverstripe/silverstripe-installer/blob/4/phpcs.xml.dist#L24

2021-09-08 09:28 UTC, TheBnl commented
The changes have been made 👍

2021-09-08 23:00 UTC, emteknetnz approved these changes

2021-09-08 23:01 UTC, merged

2021-09-08 23:01 UTC, emteknetnz commented
Thanks :)